from dataclasses import dataclass
from datetime import datetime

from openshift_ldap_operator.resources.base import (
    KubeResourceBase,
    PrintColumn,
    _field_schema,
)


@dataclass
class LdapGroupSpec:
    group_name: str = _field_schema(
        description="groupName is the short name for the group to search for (as determined by the cluster LDAPConfig).",
    )


@dataclass
class LdapGroupStatus:
    group_dn: str = _field_schema(
        description="groupDN refers to the full Distinguished Name of the group as determined by the search.",
    )
    cluster_group_name: str = _field_schema(
        description="clusterGroupName refers to the generated Group.users.openshift.io/v1 name (that would be) generated by the sync.",
    )
    last_updated_timestamp: datetime = _field_schema(
        description="lastUpdatedTimestamp refers to the time the group was last synchronized against the LDAP server.",
    )


@dataclass
class LdapGroup(KubeResourceBase):
    spec: LdapGroupSpec = _field_schema(
        description="spec defines the desired state of the LDAPGroup.",
    )
    status: LdapGroupStatus = _field_schema(
        description="status defines the observed state of the LDAPGroup.",
    )

    __group__ = "ldap.wopr.tech"
    __version__ = "v1alpha1"
    __scope__ = "cluster"
    __singular__ = "ldapgroup"
    __plural__ = "ldapgroups"
    __kind__ = "LDAPGroup"
    __short_names__ = ["lg"]
    __print_columns__ = [
        PrintColumn(
            name="Group",
            type="string",
            json_path=".spec.groupName",
            description="Name within LDAP for the group specified",
        ),
        PrintColumn(
            name="Group DN",
            type="string",
            json_path=".status.groupDN",
            priority=1,
            description="DN for the LDAP group",
        ),
        PrintColumn(
            name="Age",
            type="date",
            json_path=".metadata.creationTimestamp",
            priority=1,
        ),
        PrintColumn(
            name="Updated",
            type="date",
            json_path=".status.lastUpdatedTimestamp",
            description="Time since membership last sunchronized against LDAP",
        ),
    ]
